version: "0.1.0+{build}"

platform:
  - Win32
  - x64

environment:
  project: u
  project_sln: C:\projects\%project%\build\%project%.sln
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - msvc: 'Visual Studio 12 2013'
    - msvc: 'Visual Studio 14 2015'

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\%project%

branches:
  only:
    - master
    - dev

install:
  - git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\%project%
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%msvc%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%msvc% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: $(project_sln)
  verbosity: quiet

test_script:
  - cmd: cd C:\projects\%project%\build
  - cmd: ctest -VV
